apiVersion: v1
kind: Service
metadata:
  name: ii-simple-autos
  labels:
    app: ii-simple-autos
spec:
  type: LoadBalancer
  ports:
    - name: "http"
      port: 8080
#      //host port
      targetPort: 8080
#      //container
  selector:
    app: ii-simple-autos


